name: Test Workflow
on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      fail:
        description: 'Whether this workflow should fail'
        required: false
        type: boolean
        default: false
env:
  MY_VAR1: "Hello"
  MY_VAR2: "World"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for failure condition
        run: |
          echo "Current SHA: ${{ github.sha }}"
          echo "MY_VAR1: ${{ env.MY_VAR1 }}"
          echo "MY_VAR2: ${{ env.MY_VAR2 }}"
          if [[ "${{ inputs.fail }}" == "true" ]]; then
            echo "Simulating failure for this commit."
            exit 1
          fi
          echo "Success!"
          exit 0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Current SHA: ${{ github.sha }}"
          echo "MY_VAR1: ${{ env.MY_VAR1 }}"
          echo "MY_VAR2: ${{ env.MY_VAR2 }}"
          echo "Build Job"
          echo "Success!"
          exit 0
